# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Brouillon\MainWindow_pharmacie.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 609)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_patient = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_patient.setGeometry(QtCore.QRect(170, 160, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_patient.setFont(font)
        self.pushButton_patient.setObjectName("pushButton_patient")
        self.pushButton_medicament = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_medicament.setGeometry(QtCore.QRect(460, 160, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_medicament.setFont(font)
        self.pushButton_medicament.setObjectName("pushButton_medicament")
        self.pushButton_fournisseur = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fournisseur.setGeometry(QtCore.QRect(170, 300, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_fournisseur.setFont(font)
        self.pushButton_fournisseur.setObjectName("pushButton_fournisseur")
        self.pushButton_recherche = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_recherche.setGeometry(QtCore.QRect(460, 300, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_recherche.setFont(font)
        self.pushButton_recherche.setObjectName("pushButton_recherche")
        self.label_titre = QtWidgets.QLabel(self.centralwidget)
        self.label_titre.setGeometry(QtCore.QRect(140, 20, 621, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_titre.setFont(font)
        self.label_titre.setObjectName("label_titre")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gestion de la pharmacie Healthcare"))
        self.pushButton_patient.setText(_translate("MainWindow", "Patient"))
        self.pushButton_medicament.setText(_translate("MainWindow", "Medicament"))
        self.pushButton_fournisseur.setText(_translate("MainWindow", "Fournisseur"))
        self.pushButton_recherche.setText(_translate("MainWindow", "Rechercher"))
        self.label_titre.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0000ff;\">Bienvenue à pharmacie HealthCare !</span></p></body></html>"))
